# Configuration for golangci-lint v2. See https://golangci-lint.run/usage/configuration/.
version: "2"

linters:
  default: standard
  enable:
    - whitespace
    - govet
    - misspell
    - forcetypeassert
    - bodyclose
  exclusions:
    rules:
      - text: composite
        linters:
          - govet

formatters:
  enable:
    - gofmt
    - gci
