# Configuration for golangci-lint v2. See https://golangci-lint.run/usage/configuration/.
linters:
  default: standard
  enable:
    - gofmt
    - whitespace
    - govet
    - misspell
    - forcetypeassert
    - gci
    - bodyclose
issues:
  exclude:
    - composite
