// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tangy

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTangy creates a new instance of MockTangy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTangy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTangy {
	mock := &MockTangy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTangy is an autogenerated mock type for the Tangy type
type MockTangy struct {
	mock.Mock
}

type MockTangy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTangy) EXPECT() *MockTangy_Expecter {
	return &MockTangy_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockTangy
func (_mock *MockTangy) Close() {
	_mock.Called()
	return
}

// MockTangy_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockTangy_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockTangy_Expecter) Close() *MockTangy_Close_Call {
	return &MockTangy_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockTangy_Close_Call) Run(run func()) *MockTangy_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTangy_Close_Call) Return() *MockTangy_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTangy_Close_Call) RunAndReturn(run func()) *MockTangy_Close_Call {
	_c.Run(run)
	return _c
}

// MavenBuildList provides a mock function for the type MockTangy
func (_mock *MockTangy) MavenBuildList(ctx context.Context, repositoryHref string, groupID string, artifactID string, version string, pageOpts PageOptions) (MavenBuildListResponse, error) {
	ret := _mock.Called(ctx, repositoryHref, groupID, artifactID, version, pageOpts)

	if len(ret) == 0 {
		panic("no return value specified for MavenBuildList")
	}

	var r0 MavenBuildListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, PageOptions) (MavenBuildListResponse, error)); ok {
		return returnFunc(ctx, repositoryHref, groupID, artifactID, version, pageOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, PageOptions) MavenBuildListResponse); ok {
		r0 = returnFunc(ctx, repositoryHref, groupID, artifactID, version, pageOpts)
	} else {
		r0 = ret.Get(0).(MavenBuildListResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, PageOptions) error); ok {
		r1 = returnFunc(ctx, repositoryHref, groupID, artifactID, version, pageOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_MavenBuildList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MavenBuildList'
type MockTangy_MavenBuildList_Call struct {
	*mock.Call
}

// MavenBuildList is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryHref string
//   - groupID string
//   - artifactID string
//   - version string
//   - pageOpts PageOptions
func (_e *MockTangy_Expecter) MavenBuildList(ctx any, repositoryHref any, groupID any, artifactID any, version any, pageOpts any) *MockTangy_MavenBuildList_Call {
	return &MockTangy_MavenBuildList_Call{Call: _e.mock.On("MavenBuildList", ctx, repositoryHref, groupID, artifactID, version, pageOpts)}
}

func (_c *MockTangy_MavenBuildList_Call) Run(run func(ctx context.Context, repositoryHref string, groupID string, artifactID string, version string, pageOpts PageOptions)) *MockTangy_MavenBuildList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 PageOptions
		if args[5] != nil {
			arg5 = args[5].(PageOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockTangy_MavenBuildList_Call) Return(mavenBuildListResponse MavenBuildListResponse, err error) *MockTangy_MavenBuildList_Call {
	_c.Call.Return(mavenBuildListResponse, err)
	return _c
}

func (_c *MockTangy_MavenBuildList_Call) RunAndReturn(run func(ctx context.Context, repositoryHref string, groupID string, artifactID string, version string, pageOpts PageOptions) (MavenBuildListResponse, error)) *MockTangy_MavenBuildList_Call {
	_c.Call.Return(run)
	return _c
}

// MavenPackageList provides a mock function for the type MockTangy
func (_mock *MockTangy) MavenPackageList(ctx context.Context, repositoryHref string, filterOpts MavenPackageListFilters, pageOpts PageOptions) (MavenPackageListResponse, error) {
	ret := _mock.Called(ctx, repositoryHref, filterOpts, pageOpts)

	if len(ret) == 0 {
		panic("no return value specified for MavenPackageList")
	}

	var r0 MavenPackageListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, MavenPackageListFilters, PageOptions) (MavenPackageListResponse, error)); ok {
		return returnFunc(ctx, repositoryHref, filterOpts, pageOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, MavenPackageListFilters, PageOptions) MavenPackageListResponse); ok {
		r0 = returnFunc(ctx, repositoryHref, filterOpts, pageOpts)
	} else {
		r0 = ret.Get(0).(MavenPackageListResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, MavenPackageListFilters, PageOptions) error); ok {
		r1 = returnFunc(ctx, repositoryHref, filterOpts, pageOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_MavenPackageList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MavenPackageList'
type MockTangy_MavenPackageList_Call struct {
	*mock.Call
}

// MavenPackageList is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryHref string
//   - filterOpts MavenPackageListFilters
//   - pageOpts PageOptions
func (_e *MockTangy_Expecter) MavenPackageList(ctx any, repositoryHref any, filterOpts any, pageOpts any) *MockTangy_MavenPackageList_Call {
	return &MockTangy_MavenPackageList_Call{Call: _e.mock.On("MavenPackageList", ctx, repositoryHref, filterOpts, pageOpts)}
}

func (_c *MockTangy_MavenPackageList_Call) Run(run func(ctx context.Context, repositoryHref string, filterOpts MavenPackageListFilters, pageOpts PageOptions)) *MockTangy_MavenPackageList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 MavenPackageListFilters
		if args[2] != nil {
			arg2 = args[2].(MavenPackageListFilters)
		}
		var arg3 PageOptions
		if args[3] != nil {
			arg3 = args[3].(PageOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTangy_MavenPackageList_Call) Return(mavenPackageListResponse MavenPackageListResponse, err error) *MockTangy_MavenPackageList_Call {
	_c.Call.Return(mavenPackageListResponse, err)
	return _c
}

func (_c *MockTangy_MavenPackageList_Call) RunAndReturn(run func(ctx context.Context, repositoryHref string, filterOpts MavenPackageListFilters, pageOpts PageOptions) (MavenPackageListResponse, error)) *MockTangy_MavenPackageList_Call {
	_c.Call.Return(run)
	return _c
}

// MavenRepositoryMetrics provides a mock function for the type MockTangy
func (_mock *MockTangy) MavenRepositoryMetrics(ctx context.Context, repositoryHref string) (MavenRepositoryMetrics, error) {
	ret := _mock.Called(ctx, repositoryHref)

	if len(ret) == 0 {
		panic("no return value specified for MavenRepositoryMetrics")
	}

	var r0 MavenRepositoryMetrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (MavenRepositoryMetrics, error)); ok {
		return returnFunc(ctx, repositoryHref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) MavenRepositoryMetrics); ok {
		r0 = returnFunc(ctx, repositoryHref)
	} else {
		r0 = ret.Get(0).(MavenRepositoryMetrics)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repositoryHref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_MavenRepositoryMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MavenRepositoryMetrics'
type MockTangy_MavenRepositoryMetrics_Call struct {
	*mock.Call
}

// MavenRepositoryMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryHref string
func (_e *MockTangy_Expecter) MavenRepositoryMetrics(ctx any, repositoryHref any) *MockTangy_MavenRepositoryMetrics_Call {
	return &MockTangy_MavenRepositoryMetrics_Call{Call: _e.mock.On("MavenRepositoryMetrics", ctx, repositoryHref)}
}

func (_c *MockTangy_MavenRepositoryMetrics_Call) Run(run func(ctx context.Context, repositoryHref string)) *MockTangy_MavenRepositoryMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTangy_MavenRepositoryMetrics_Call) Return(mavenRepositoryMetrics MavenRepositoryMetrics, err error) *MockTangy_MavenRepositoryMetrics_Call {
	_c.Call.Return(mavenRepositoryMetrics, err)
	return _c
}

func (_c *MockTangy_MavenRepositoryMetrics_Call) RunAndReturn(run func(ctx context.Context, repositoryHref string) (MavenRepositoryMetrics, error)) *MockTangy_MavenRepositoryMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// PythonBuildList provides a mock function for the type MockTangy
func (_mock *MockTangy) PythonBuildList(ctx context.Context, repositoryHref string, nameNormalized string, version string, pageOpts PageOptions) (PythonBuildListResponse, error) {
	ret := _mock.Called(ctx, repositoryHref, nameNormalized, version, pageOpts)

	if len(ret) == 0 {
		panic("no return value specified for PythonBuildList")
	}

	var r0 PythonBuildListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, PageOptions) (PythonBuildListResponse, error)); ok {
		return returnFunc(ctx, repositoryHref, nameNormalized, version, pageOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, PageOptions) PythonBuildListResponse); ok {
		r0 = returnFunc(ctx, repositoryHref, nameNormalized, version, pageOpts)
	} else {
		r0 = ret.Get(0).(PythonBuildListResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, PageOptions) error); ok {
		r1 = returnFunc(ctx, repositoryHref, nameNormalized, version, pageOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_PythonBuildList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PythonBuildList'
type MockTangy_PythonBuildList_Call struct {
	*mock.Call
}

// PythonBuildList is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryHref string
//   - nameNormalized string
//   - version string
//   - pageOpts PageOptions
func (_e *MockTangy_Expecter) PythonBuildList(ctx any, repositoryHref any, nameNormalized any, version any, pageOpts any) *MockTangy_PythonBuildList_Call {
	return &MockTangy_PythonBuildList_Call{Call: _e.mock.On("PythonBuildList", ctx, repositoryHref, nameNormalized, version, pageOpts)}
}

func (_c *MockTangy_PythonBuildList_Call) Run(run func(ctx context.Context, repositoryHref string, nameNormalized string, version string, pageOpts PageOptions)) *MockTangy_PythonBuildList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 PageOptions
		if args[4] != nil {
			arg4 = args[4].(PageOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTangy_PythonBuildList_Call) Return(pythonBuildListResponse PythonBuildListResponse, err error) *MockTangy_PythonBuildList_Call {
	_c.Call.Return(pythonBuildListResponse, err)
	return _c
}

func (_c *MockTangy_PythonBuildList_Call) RunAndReturn(run func(ctx context.Context, repositoryHref string, nameNormalized string, version string, pageOpts PageOptions) (PythonBuildListResponse, error)) *MockTangy_PythonBuildList_Call {
	_c.Call.Return(run)
	return _c
}

// PythonDistributionList provides a mock function for the type MockTangy
func (_mock *MockTangy) PythonDistributionList(ctx context.Context, repositoryHref string, nameNormalized string, version string, pageOpts PageOptions) (PythonDistributionListResponse, error) {
	ret := _mock.Called(ctx, repositoryHref, nameNormalized, version, pageOpts)

	if len(ret) == 0 {
		panic("no return value specified for PythonDistributionList")
	}

	var r0 PythonDistributionListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, PageOptions) (PythonDistributionListResponse, error)); ok {
		return returnFunc(ctx, repositoryHref, nameNormalized, version, pageOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, PageOptions) PythonDistributionListResponse); ok {
		r0 = returnFunc(ctx, repositoryHref, nameNormalized, version, pageOpts)
	} else {
		r0 = ret.Get(0).(PythonDistributionListResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, PageOptions) error); ok {
		r1 = returnFunc(ctx, repositoryHref, nameNormalized, version, pageOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_PythonDistributionList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PythonDistributionList'
type MockTangy_PythonDistributionList_Call struct {
	*mock.Call
}

// PythonDistributionList is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryHref string
//   - nameNormalized string
//   - version string
//   - pageOpts PageOptions
func (_e *MockTangy_Expecter) PythonDistributionList(ctx any, repositoryHref any, nameNormalized any, version any, pageOpts any) *MockTangy_PythonDistributionList_Call {
	return &MockTangy_PythonDistributionList_Call{Call: _e.mock.On("PythonDistributionList", ctx, repositoryHref, nameNormalized, version, pageOpts)}
}

func (_c *MockTangy_PythonDistributionList_Call) Run(run func(ctx context.Context, repositoryHref string, nameNormalized string, version string, pageOpts PageOptions)) *MockTangy_PythonDistributionList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 PageOptions
		if args[4] != nil {
			arg4 = args[4].(PageOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTangy_PythonDistributionList_Call) Return(pythonDistributionListResponse PythonDistributionListResponse, err error) *MockTangy_PythonDistributionList_Call {
	_c.Call.Return(pythonDistributionListResponse, err)
	return _c
}

func (_c *MockTangy_PythonDistributionList_Call) RunAndReturn(run func(ctx context.Context, repositoryHref string, nameNormalized string, version string, pageOpts PageOptions) (PythonDistributionListResponse, error)) *MockTangy_PythonDistributionList_Call {
	_c.Call.Return(run)
	return _c
}

// PythonPackageGet provides a mock function for the type MockTangy
func (_mock *MockTangy) PythonPackageGet(ctx context.Context, repositoryHref string, nameNormalized string, version string) (PythonPackageDetail, error) {
	ret := _mock.Called(ctx, repositoryHref, nameNormalized, version)

	if len(ret) == 0 {
		panic("no return value specified for PythonPackageGet")
	}

	var r0 PythonPackageDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (PythonPackageDetail, error)); ok {
		return returnFunc(ctx, repositoryHref, nameNormalized, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) PythonPackageDetail); ok {
		r0 = returnFunc(ctx, repositoryHref, nameNormalized, version)
	} else {
		r0 = ret.Get(0).(PythonPackageDetail)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, repositoryHref, nameNormalized, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_PythonPackageGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PythonPackageGet'
type MockTangy_PythonPackageGet_Call struct {
	*mock.Call
}

// PythonPackageGet is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryHref string
//   - nameNormalized string
//   - version string
func (_e *MockTangy_Expecter) PythonPackageGet(ctx any, repositoryHref any, nameNormalized any, version any) *MockTangy_PythonPackageGet_Call {
	return &MockTangy_PythonPackageGet_Call{Call: _e.mock.On("PythonPackageGet", ctx, repositoryHref, nameNormalized, version)}
}

func (_c *MockTangy_PythonPackageGet_Call) Run(run func(ctx context.Context, repositoryHref string, nameNormalized string, version string)) *MockTangy_PythonPackageGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTangy_PythonPackageGet_Call) Return(pythonPackageDetail PythonPackageDetail, err error) *MockTangy_PythonPackageGet_Call {
	_c.Call.Return(pythonPackageDetail, err)
	return _c
}

func (_c *MockTangy_PythonPackageGet_Call) RunAndReturn(run func(ctx context.Context, repositoryHref string, nameNormalized string, version string) (PythonPackageDetail, error)) *MockTangy_PythonPackageGet_Call {
	_c.Call.Return(run)
	return _c
}

// PythonPackageList provides a mock function for the type MockTangy
func (_mock *MockTangy) PythonPackageList(ctx context.Context, repositoryHref string, filterOpts PythonPackageListFilters, pageOpts PageOptions) (PythonPackageListResponse, error) {
	ret := _mock.Called(ctx, repositoryHref, filterOpts, pageOpts)

	if len(ret) == 0 {
		panic("no return value specified for PythonPackageList")
	}

	var r0 PythonPackageListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, PythonPackageListFilters, PageOptions) (PythonPackageListResponse, error)); ok {
		return returnFunc(ctx, repositoryHref, filterOpts, pageOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, PythonPackageListFilters, PageOptions) PythonPackageListResponse); ok {
		r0 = returnFunc(ctx, repositoryHref, filterOpts, pageOpts)
	} else {
		r0 = ret.Get(0).(PythonPackageListResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, PythonPackageListFilters, PageOptions) error); ok {
		r1 = returnFunc(ctx, repositoryHref, filterOpts, pageOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_PythonPackageList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PythonPackageList'
type MockTangy_PythonPackageList_Call struct {
	*mock.Call
}

// PythonPackageList is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryHref string
//   - filterOpts PythonPackageListFilters
//   - pageOpts PageOptions
func (_e *MockTangy_Expecter) PythonPackageList(ctx any, repositoryHref any, filterOpts any, pageOpts any) *MockTangy_PythonPackageList_Call {
	return &MockTangy_PythonPackageList_Call{Call: _e.mock.On("PythonPackageList", ctx, repositoryHref, filterOpts, pageOpts)}
}

func (_c *MockTangy_PythonPackageList_Call) Run(run func(ctx context.Context, repositoryHref string, filterOpts PythonPackageListFilters, pageOpts PageOptions)) *MockTangy_PythonPackageList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 PythonPackageListFilters
		if args[2] != nil {
			arg2 = args[2].(PythonPackageListFilters)
		}
		var arg3 PageOptions
		if args[3] != nil {
			arg3 = args[3].(PageOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTangy_PythonPackageList_Call) Return(pythonPackageListResponse PythonPackageListResponse, err error) *MockTangy_PythonPackageList_Call {
	_c.Call.Return(pythonPackageListResponse, err)
	return _c
}

func (_c *MockTangy_PythonPackageList_Call) RunAndReturn(run func(ctx context.Context, repositoryHref string, filterOpts PythonPackageListFilters, pageOpts PageOptions) (PythonPackageListResponse, error)) *MockTangy_PythonPackageList_Call {
	_c.Call.Return(run)
	return _c
}

// PythonPackageVersionsGet provides a mock function for the type MockTangy
func (_mock *MockTangy) PythonPackageVersionsGet(ctx context.Context, repositoryHref string, nameNormalized string) ([]PythonPackageDetail, error) {
	ret := _mock.Called(ctx, repositoryHref, nameNormalized)

	if len(ret) == 0 {
		panic("no return value specified for PythonPackageVersionsGet")
	}

	var r0 []PythonPackageDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]PythonPackageDetail, error)); ok {
		return returnFunc(ctx, repositoryHref, nameNormalized)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []PythonPackageDetail); ok {
		r0 = returnFunc(ctx, repositoryHref, nameNormalized)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PythonPackageDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, repositoryHref, nameNormalized)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_PythonPackageVersionsGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PythonPackageVersionsGet'
type MockTangy_PythonPackageVersionsGet_Call struct {
	*mock.Call
}

// PythonPackageVersionsGet is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryHref string
//   - nameNormalized string
func (_e *MockTangy_Expecter) PythonPackageVersionsGet(ctx any, repositoryHref any, nameNormalized any) *MockTangy_PythonPackageVersionsGet_Call {
	return &MockTangy_PythonPackageVersionsGet_Call{Call: _e.mock.On("PythonPackageVersionsGet", ctx, repositoryHref, nameNormalized)}
}

func (_c *MockTangy_PythonPackageVersionsGet_Call) Run(run func(ctx context.Context, repositoryHref string, nameNormalized string)) *MockTangy_PythonPackageVersionsGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTangy_PythonPackageVersionsGet_Call) Return(pythonPackageDetails []PythonPackageDetail, err error) *MockTangy_PythonPackageVersionsGet_Call {
	_c.Call.Return(pythonPackageDetails, err)
	return _c
}

func (_c *MockTangy_PythonPackageVersionsGet_Call) RunAndReturn(run func(ctx context.Context, repositoryHref string, nameNormalized string) ([]PythonPackageDetail, error)) *MockTangy_PythonPackageVersionsGet_Call {
	_c.Call.Return(run)
	return _c
}

// PythonRepositoryMetrics provides a mock function for the type MockTangy
func (_mock *MockTangy) PythonRepositoryMetrics(ctx context.Context, repositoryHref string) (PythonRepositoryMetrics, error) {
	ret := _mock.Called(ctx, repositoryHref)

	if len(ret) == 0 {
		panic("no return value specified for PythonRepositoryMetrics")
	}

	var r0 PythonRepositoryMetrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (PythonRepositoryMetrics, error)); ok {
		return returnFunc(ctx, repositoryHref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) PythonRepositoryMetrics); ok {
		r0 = returnFunc(ctx, repositoryHref)
	} else {
		r0 = ret.Get(0).(PythonRepositoryMetrics)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repositoryHref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_PythonRepositoryMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PythonRepositoryMetrics'
type MockTangy_PythonRepositoryMetrics_Call struct {
	*mock.Call
}

// PythonRepositoryMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryHref string
func (_e *MockTangy_Expecter) PythonRepositoryMetrics(ctx any, repositoryHref any) *MockTangy_PythonRepositoryMetrics_Call {
	return &MockTangy_PythonRepositoryMetrics_Call{Call: _e.mock.On("PythonRepositoryMetrics", ctx, repositoryHref)}
}

func (_c *MockTangy_PythonRepositoryMetrics_Call) Run(run func(ctx context.Context, repositoryHref string)) *MockTangy_PythonRepositoryMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTangy_PythonRepositoryMetrics_Call) Return(pythonRepositoryMetrics PythonRepositoryMetrics, err error) *MockTangy_PythonRepositoryMetrics_Call {
	_c.Call.Return(pythonRepositoryMetrics, err)
	return _c
}

func (_c *MockTangy_PythonRepositoryMetrics_Call) RunAndReturn(run func(ctx context.Context, repositoryHref string) (PythonRepositoryMetrics, error)) *MockTangy_PythonRepositoryMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// RpmRepositoryVersionEnvironmentSearch provides a mock function for the type MockTangy
func (_mock *MockTangy) RpmRepositoryVersionEnvironmentSearch(ctx context.Context, hrefs []string, search string, limit int) ([]RpmEnvironmentSearch, error) {
	ret := _mock.Called(ctx, hrefs, search, limit)

	if len(ret) == 0 {
		panic("no return value specified for RpmRepositoryVersionEnvironmentSearch")
	}

	var r0 []RpmEnvironmentSearch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, int) ([]RpmEnvironmentSearch, error)); ok {
		return returnFunc(ctx, hrefs, search, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, int) []RpmEnvironmentSearch); ok {
		r0 = returnFunc(ctx, hrefs, search, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RpmEnvironmentSearch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, string, int) error); ok {
		r1 = returnFunc(ctx, hrefs, search, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_RpmRepositoryVersionEnvironmentSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RpmRepositoryVersionEnvironmentSearch'
type MockTangy_RpmRepositoryVersionEnvironmentSearch_Call struct {
	*mock.Call
}

// RpmRepositoryVersionEnvironmentSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - hrefs []string
//   - search string
//   - limit int
func (_e *MockTangy_Expecter) RpmRepositoryVersionEnvironmentSearch(ctx any, hrefs any, search any, limit any) *MockTangy_RpmRepositoryVersionEnvironmentSearch_Call {
	return &MockTangy_RpmRepositoryVersionEnvironmentSearch_Call{Call: _e.mock.On("RpmRepositoryVersionEnvironmentSearch", ctx, hrefs, search, limit)}
}

func (_c *MockTangy_RpmRepositoryVersionEnvironmentSearch_Call) Run(run func(ctx context.Context, hrefs []string, search string, limit int)) *MockTangy_RpmRepositoryVersionEnvironmentSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionEnvironmentSearch_Call) Return(rpmEnvironmentSearchs []RpmEnvironmentSearch, err error) *MockTangy_RpmRepositoryVersionEnvironmentSearch_Call {
	_c.Call.Return(rpmEnvironmentSearchs, err)
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionEnvironmentSearch_Call) RunAndReturn(run func(ctx context.Context, hrefs []string, search string, limit int) ([]RpmEnvironmentSearch, error)) *MockTangy_RpmRepositoryVersionEnvironmentSearch_Call {
	_c.Call.Return(run)
	return _c
}

// RpmRepositoryVersionErrataList provides a mock function for the type MockTangy
func (_mock *MockTangy) RpmRepositoryVersionErrataList(ctx context.Context, hrefs []string, filterOpts ErrataListFilters, pageOpts PageOptions) ([]ErrataListItem, int, error) {
	ret := _mock.Called(ctx, hrefs, filterOpts, pageOpts)

	if len(ret) == 0 {
		panic("no return value specified for RpmRepositoryVersionErrataList")
	}

	var r0 []ErrataListItem
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ErrataListFilters, PageOptions) ([]ErrataListItem, int, error)); ok {
		return returnFunc(ctx, hrefs, filterOpts, pageOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ErrataListFilters, PageOptions) []ErrataListItem); ok {
		r0 = returnFunc(ctx, hrefs, filterOpts, pageOpts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ErrataListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, ErrataListFilters, PageOptions) int); ok {
		r1 = returnFunc(ctx, hrefs, filterOpts, pageOpts)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []string, ErrataListFilters, PageOptions) error); ok {
		r2 = returnFunc(ctx, hrefs, filterOpts, pageOpts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTangy_RpmRepositoryVersionErrataList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RpmRepositoryVersionErrataList'
type MockTangy_RpmRepositoryVersionErrataList_Call struct {
	*mock.Call
}

// RpmRepositoryVersionErrataList is a helper method to define mock.On call
//   - ctx context.Context
//   - hrefs []string
//   - filterOpts ErrataListFilters
//   - pageOpts PageOptions
func (_e *MockTangy_Expecter) RpmRepositoryVersionErrataList(ctx any, hrefs any, filterOpts any, pageOpts any) *MockTangy_RpmRepositoryVersionErrataList_Call {
	return &MockTangy_RpmRepositoryVersionErrataList_Call{Call: _e.mock.On("RpmRepositoryVersionErrataList", ctx, hrefs, filterOpts, pageOpts)}
}

func (_c *MockTangy_RpmRepositoryVersionErrataList_Call) Run(run func(ctx context.Context, hrefs []string, filterOpts ErrataListFilters, pageOpts PageOptions)) *MockTangy_RpmRepositoryVersionErrataList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 ErrataListFilters
		if args[2] != nil {
			arg2 = args[2].(ErrataListFilters)
		}
		var arg3 PageOptions
		if args[3] != nil {
			arg3 = args[3].(PageOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionErrataList_Call) Return(errataListItems []ErrataListItem, n int, err error) *MockTangy_RpmRepositoryVersionErrataList_Call {
	_c.Call.Return(errataListItems, n, err)
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionErrataList_Call) RunAndReturn(run func(ctx context.Context, hrefs []string, filterOpts ErrataListFilters, pageOpts PageOptions) ([]ErrataListItem, int, error)) *MockTangy_RpmRepositoryVersionErrataList_Call {
	_c.Call.Return(run)
	return _c
}

// RpmRepositoryVersionModuleStreamsList provides a mock function for the type MockTangy
func (_mock *MockTangy) RpmRepositoryVersionModuleStreamsList(ctx context.Context, hrefs []string, filterOpts ModuleStreamListFilters, sortBy string) ([]ModuleStreams, error) {
	ret := _mock.Called(ctx, hrefs, filterOpts, sortBy)

	if len(ret) == 0 {
		panic("no return value specified for RpmRepositoryVersionModuleStreamsList")
	}

	var r0 []ModuleStreams
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ModuleStreamListFilters, string) ([]ModuleStreams, error)); ok {
		return returnFunc(ctx, hrefs, filterOpts, sortBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ModuleStreamListFilters, string) []ModuleStreams); ok {
		r0 = returnFunc(ctx, hrefs, filterOpts, sortBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ModuleStreams)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, ModuleStreamListFilters, string) error); ok {
		r1 = returnFunc(ctx, hrefs, filterOpts, sortBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_RpmRepositoryVersionModuleStreamsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RpmRepositoryVersionModuleStreamsList'
type MockTangy_RpmRepositoryVersionModuleStreamsList_Call struct {
	*mock.Call
}

// RpmRepositoryVersionModuleStreamsList is a helper method to define mock.On call
//   - ctx context.Context
//   - hrefs []string
//   - filterOpts ModuleStreamListFilters
//   - sortBy string
func (_e *MockTangy_Expecter) RpmRepositoryVersionModuleStreamsList(ctx any, hrefs any, filterOpts any, sortBy any) *MockTangy_RpmRepositoryVersionModuleStreamsList_Call {
	return &MockTangy_RpmRepositoryVersionModuleStreamsList_Call{Call: _e.mock.On("RpmRepositoryVersionModuleStreamsList", ctx, hrefs, filterOpts, sortBy)}
}

func (_c *MockTangy_RpmRepositoryVersionModuleStreamsList_Call) Run(run func(ctx context.Context, hrefs []string, filterOpts ModuleStreamListFilters, sortBy string)) *MockTangy_RpmRepositoryVersionModuleStreamsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 ModuleStreamListFilters
		if args[2] != nil {
			arg2 = args[2].(ModuleStreamListFilters)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionModuleStreamsList_Call) Return(moduleStreamss []ModuleStreams, err error) *MockTangy_RpmRepositoryVersionModuleStreamsList_Call {
	_c.Call.Return(moduleStreamss, err)
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionModuleStreamsList_Call) RunAndReturn(run func(ctx context.Context, hrefs []string, filterOpts ModuleStreamListFilters, sortBy string) ([]ModuleStreams, error)) *MockTangy_RpmRepositoryVersionModuleStreamsList_Call {
	_c.Call.Return(run)
	return _c
}

// RpmRepositoryVersionPackageGroupSearch provides a mock function for the type MockTangy
func (_mock *MockTangy) RpmRepositoryVersionPackageGroupSearch(ctx context.Context, hrefs []string, search string, limit int) ([]RpmPackageGroupSearch, error) {
	ret := _mock.Called(ctx, hrefs, search, limit)

	if len(ret) == 0 {
		panic("no return value specified for RpmRepositoryVersionPackageGroupSearch")
	}

	var r0 []RpmPackageGroupSearch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, int) ([]RpmPackageGroupSearch, error)); ok {
		return returnFunc(ctx, hrefs, search, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, int) []RpmPackageGroupSearch); ok {
		r0 = returnFunc(ctx, hrefs, search, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RpmPackageGroupSearch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, string, int) error); ok {
		r1 = returnFunc(ctx, hrefs, search, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_RpmRepositoryVersionPackageGroupSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RpmRepositoryVersionPackageGroupSearch'
type MockTangy_RpmRepositoryVersionPackageGroupSearch_Call struct {
	*mock.Call
}

// RpmRepositoryVersionPackageGroupSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - hrefs []string
//   - search string
//   - limit int
func (_e *MockTangy_Expecter) RpmRepositoryVersionPackageGroupSearch(ctx any, hrefs any, search any, limit any) *MockTangy_RpmRepositoryVersionPackageGroupSearch_Call {
	return &MockTangy_RpmRepositoryVersionPackageGroupSearch_Call{Call: _e.mock.On("RpmRepositoryVersionPackageGroupSearch", ctx, hrefs, search, limit)}
}

func (_c *MockTangy_RpmRepositoryVersionPackageGroupSearch_Call) Run(run func(ctx context.Context, hrefs []string, search string, limit int)) *MockTangy_RpmRepositoryVersionPackageGroupSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionPackageGroupSearch_Call) Return(rpmPackageGroupSearchs []RpmPackageGroupSearch, err error) *MockTangy_RpmRepositoryVersionPackageGroupSearch_Call {
	_c.Call.Return(rpmPackageGroupSearchs, err)
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionPackageGroupSearch_Call) RunAndReturn(run func(ctx context.Context, hrefs []string, search string, limit int) ([]RpmPackageGroupSearch, error)) *MockTangy_RpmRepositoryVersionPackageGroupSearch_Call {
	_c.Call.Return(run)
	return _c
}

// RpmRepositoryVersionPackageList provides a mock function for the type MockTangy
func (_mock *MockTangy) RpmRepositoryVersionPackageList(ctx context.Context, hrefs []string, filterOpts RpmListFilters, pageOpts PageOptions) ([]RpmListItem, int, error) {
	ret := _mock.Called(ctx, hrefs, filterOpts, pageOpts)

	if len(ret) == 0 {
		panic("no return value specified for RpmRepositoryVersionPackageList")
	}

	var r0 []RpmListItem
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, RpmListFilters, PageOptions) ([]RpmListItem, int, error)); ok {
		return returnFunc(ctx, hrefs, filterOpts, pageOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, RpmListFilters, PageOptions) []RpmListItem); ok {
		r0 = returnFunc(ctx, hrefs, filterOpts, pageOpts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RpmListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, RpmListFilters, PageOptions) int); ok {
		r1 = returnFunc(ctx, hrefs, filterOpts, pageOpts)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []string, RpmListFilters, PageOptions) error); ok {
		r2 = returnFunc(ctx, hrefs, filterOpts, pageOpts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTangy_RpmRepositoryVersionPackageList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RpmRepositoryVersionPackageList'
type MockTangy_RpmRepositoryVersionPackageList_Call struct {
	*mock.Call
}

// RpmRepositoryVersionPackageList is a helper method to define mock.On call
//   - ctx context.Context
//   - hrefs []string
//   - filterOpts RpmListFilters
//   - pageOpts PageOptions
func (_e *MockTangy_Expecter) RpmRepositoryVersionPackageList(ctx any, hrefs any, filterOpts any, pageOpts any) *MockTangy_RpmRepositoryVersionPackageList_Call {
	return &MockTangy_RpmRepositoryVersionPackageList_Call{Call: _e.mock.On("RpmRepositoryVersionPackageList", ctx, hrefs, filterOpts, pageOpts)}
}

func (_c *MockTangy_RpmRepositoryVersionPackageList_Call) Run(run func(ctx context.Context, hrefs []string, filterOpts RpmListFilters, pageOpts PageOptions)) *MockTangy_RpmRepositoryVersionPackageList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 RpmListFilters
		if args[2] != nil {
			arg2 = args[2].(RpmListFilters)
		}
		var arg3 PageOptions
		if args[3] != nil {
			arg3 = args[3].(PageOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionPackageList_Call) Return(rpmListItems []RpmListItem, n int, err error) *MockTangy_RpmRepositoryVersionPackageList_Call {
	_c.Call.Return(rpmListItems, n, err)
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionPackageList_Call) RunAndReturn(run func(ctx context.Context, hrefs []string, filterOpts RpmListFilters, pageOpts PageOptions) ([]RpmListItem, int, error)) *MockTangy_RpmRepositoryVersionPackageList_Call {
	_c.Call.Return(run)
	return _c
}

// RpmRepositoryVersionPackageSearch provides a mock function for the type MockTangy
func (_mock *MockTangy) RpmRepositoryVersionPackageSearch(ctx context.Context, hrefs []string, search string, limit int) ([]RpmPackageSearch, error) {
	ret := _mock.Called(ctx, hrefs, search, limit)

	if len(ret) == 0 {
		panic("no return value specified for RpmRepositoryVersionPackageSearch")
	}

	var r0 []RpmPackageSearch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, int) ([]RpmPackageSearch, error)); ok {
		return returnFunc(ctx, hrefs, search, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, int) []RpmPackageSearch); ok {
		r0 = returnFunc(ctx, hrefs, search, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RpmPackageSearch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, string, int) error); ok {
		r1 = returnFunc(ctx, hrefs, search, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTangy_RpmRepositoryVersionPackageSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RpmRepositoryVersionPackageSearch'
type MockTangy_RpmRepositoryVersionPackageSearch_Call struct {
	*mock.Call
}

// RpmRepositoryVersionPackageSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - hrefs []string
//   - search string
//   - limit int
func (_e *MockTangy_Expecter) RpmRepositoryVersionPackageSearch(ctx any, hrefs any, search any, limit any) *MockTangy_RpmRepositoryVersionPackageSearch_Call {
	return &MockTangy_RpmRepositoryVersionPackageSearch_Call{Call: _e.mock.On("RpmRepositoryVersionPackageSearch", ctx, hrefs, search, limit)}
}

func (_c *MockTangy_RpmRepositoryVersionPackageSearch_Call) Run(run func(ctx context.Context, hrefs []string, search string, limit int)) *MockTangy_RpmRepositoryVersionPackageSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionPackageSearch_Call) Return(rpmPackageSearchs []RpmPackageSearch, err error) *MockTangy_RpmRepositoryVersionPackageSearch_Call {
	_c.Call.Return(rpmPackageSearchs, err)
	return _c
}

func (_c *MockTangy_RpmRepositoryVersionPackageSearch_Call) RunAndReturn(run func(ctx context.Context, hrefs []string, search string, limit int) ([]RpmPackageSearch, error)) *MockTangy_RpmRepositoryVersionPackageSearch_Call {
	_c.Call.Return(run)
	return _c
}
