name: build-test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.22"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
          skip-go-installation: true
          args: --timeout=5m
  gotest:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.22"
      - name: start pulp
        uses: isbang/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yml
          cwd: ./compose_files/pulp/
          down-flags: --volumes
      - name: Wait for pulp
        run: |
          docker run --network=host --rm -v ${PWD}:/local curlimages/curl  \
          curl --retry-all-errors --fail --retry-delay 10 --retry 32 --retry-max-time 240 http://localhost:8087/api/pulp/default/api/v3/repositories/rpm/rpm/  -u admin:password
          sleep 30
      - name: integration tests
        run: |
          make test-integration
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5434
          DATABASE_USER: pulp
          DATABASE_NAME: pulp
          DATABASE_PASSWORD: password
          SERVER_URL: http://localhost:8087
          SERVER_USERNAME: admin
          SERVER_PASSWORD: password
